blank_issues_enabled: true
contact_links:
  - name: WESTPA User Community Support
    url: https://groups.google.com/g/westpa-users
    about: Please ask and answer questions here about using/running WESTPA.
  - name: WESTPA Developer Discussions
    url: https://groups.google.com/g/westpa-devel
    about: For more informal discussions on developing/improving WESTPA, ask your questions here.
